project_id = "icggemcoeiwbhtgekkby"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.signature-webhook]
    verify_jwt = false
  [functions.admission-public]
    verify_jwt = false
